sudo: required
services:
  - docker

before_install:
  - docker build -t xd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xd/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-870360677158"
  bucket:path: "docker"
  on: 
    branch: master 
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"