FROM node:16-alpine

RUN mkdir -p /home/xuandong93/frontend

WORKDIR '/home/xuandong93/frontend'

USER node

COPY --chown=node:node ./package.json ./

RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]